name: Sync articles

on:
  schedule:
    - cron: 0 8 * * *
  workflow_dispatch:

jobs:
  update-axone-blog-section:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.OPS_TOKEN }}

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.BOT_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.BOT_GPG_PASSPHRASE }}
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Update README with latest Axone articles
        uses: JasonEtco/rss-to-readme@v2
        with:
          feed_url: "https://blog.axone.xyz/feed"
          readme-section: "axone-medium"
          max: 15
          template: "- 📝 [{{ title }}]({{ link }}) — {{ pubDate }}"

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_user_name: ${{ vars.BOT_GIT_COMMITTER_NAME }}
          commit_user_email: ${{ vars.BOT_GIT_COMMITTER_EMAIL }}
          commit_author: ${{ vars.BOT_GIT_AUTHOR_NAME }} <${{ vars.BOT_GIT_AUTHOR_EMAIL }}>
          commit_message: "feat(README): update Axone articles section"
