name: Sync articles

on:
  schedule:
    - cron: 0 8 * * *
  workflow_dispatch:

jobs:
  update-axone-blog-section:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.OPS_TOKEN }}

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.BOT_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.BOT_GPG_PASSPHRASE }}
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Install dependencies
        run: pip install feedparser

      - name: Update Axone articles section
        shell: python
        run: |
          import feedparser
          import re
          import sys

          README = "README.md"
          FEED_URL = "https://blog.axone.xyz/feed"
          START = "<!--START_SECTION:axone-medium-->"
          END = "<!--END_SECTION:axone-medium-->"
          MAX_ITEMS = 10

          feed = feedparser.parse(FEED_URL)

          lines = []
          for entry in feed.entries[:MAX_ITEMS]:
              title = getattr(entry, "title", "").strip()
              link = getattr(entry, "link", "").strip()
              pub = getattr(entry, "published", "").strip()
              if title and link:
                  lines.append(f"- 📝 [{title}]({link}) — {pub}")

          with open(README, "r", encoding="utf-8") as f:
              content = f.read()

          pattern = re.compile(f"{re.escape(START)}.*?{re.escape(END)}", re.DOTALL)
          if not pattern.search(content):
              sys.exit("Start or end marker not found in README.md")

          new_block = f"{START}\n" + "\n".join(lines) + f"\n{END}"
          updated = pattern.sub(new_block, content)

          with open(README, "w", encoding="utf-8") as f:
              f.write(updated)

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_user_name: ${{ vars.BOT_GIT_COMMITTER_NAME }}
          commit_user_email: ${{ vars.BOT_GIT_COMMITTER_EMAIL }}
          commit_author: ${{ vars.BOT_GIT_AUTHOR_NAME }} <${{ vars.BOT_GIT_AUTHOR_EMAIL }}>
          commit_message: "feat(README): update Axone articles section"
